### ISSUE TITLE
Save states not working in latest PCSX4ALL

### ISSUE THREAD

**Issue by Dantasstic** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#16]
States will save, but will not load properly. 

Using Rogue 1.0.3 and the latest pcsx4all.opk. I have tried both with and without a PS1 bios.

**Comment by Ninoh-FOX** [comment]
lo probé el otro dia al ver tu comentario y a mi me funciona bien

**Comment by Dantasstic** [comment]
Try it in Silent Hill

**Comment by Dantasstic** [comment]
I removed the opk and then redownloaded it from the link. It is working now, thanks!
