### ISSUE TITLE
Rogue 1.0.3 - Laggy gaming as soon as I turn it on

### ISSUE THREAD

**Issue by ecsj88** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#17]
I have noticed that from time to time games lag for a couple of minutes as soon as I turn the PG2 on if I hadn't been playing with it for a couple of hours. Sometimes I gotta restart it twice to make games run smoothly. Is this a common problem for this update? It didnt happen with version 1.0.2

**Comment by Ninoh-FOX** [comment]
I haven't noticed any of that yet, let's see if I play a little and confirm it. In which game, emulator, have you noticed them?

**Comment by ecsj88** [comment]
Suddenly everything is okay for the past 5 days! It was acting like that for Street Fighter 3: Third Strike and Three Wonders, both for FBA. Megaman X for SNES and Super Mario Bros 2 For NES. I have tested them all again and no problem.
