### ISSUE TITLE
Can't use the stick of my PocketGo anymore :S

### ISSUE THREAD

**Issue by IIBendoGII** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#19]
Any1 know how to fix that?  I can see that the stick is working on the button testing programm, but in the menu or the emulators I can't use it. Instead of the snes emulator but I have to change joystick    "on" in the settings O.o

**Comment by Ninoh-FOX** [comment]
You can't use the analog stick in all emulators, only a little part, but you can change/switch the stick to dpad with power+B

**Comment by IIBendoGII** [comment]
Ah ok, that works fine for me, thank you <3 

Greetings from germany and sorry for my bad english :D

**Comment by Ninoh-FOX** [comment]
Ok
