### ISSUE TITLE
emulationstation Could not initialize OpenGL

### ISSUE THREAD

**Issue by etrombly** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#2]
Followed the instructions here https://github.com/ManuelSch81/RG350-EmulationStation_configured to install emulationstation. When launching the es_log.txt says it was unable to initialize opengl. Looks like the rogue firmware for the rg-350 is giving the same error. https://boards.dingoonity.org/retro-game-350rg-350/rg350-'rogue'-cfw/msg192879/#msg192879

**Comment by Ninoh-FOX** [comment]
Yes, I know, this weekend I go to make a release that fix this.

**Comment by etrombly** [comment]
awesome, thank you

**Comment by Ninoh-FOX** [comment]
fixed in the new release 1.0.3
