### ISSUE TITLE
"Save last selection" only works if each game is in its own folder

### ISSUE THREAD

**Issue by DsChAeK** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#23]
Menu setting "Save last selection" only works for PS1 games, where each game is in its own folder.
I'm using the /media/data/roms/ folder on SD1 with CFW 1.0.4 e.g. /media/data/roms/GB/*.zip
If I click an emulator and select a game, quit to menu and reselect the emulator, the selection is always on the first ".." entry. 

What could be the reason for this behaviour?

Thx in advance!

**Comment by Ninoh-FOX** [comment]
done in update 1.1
