### ISSUE TITLE
Clock time doesn't save when powering off

### ISSUE THREAD

**Issue by Johnny56732** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#24]
The time is always wrong, and when I adjust for the correct time save it & exit then power off and turn on again the click shows the wrong time and didn't save the changes that I made
It's currently 5:59pm in the U.S. where I'm at and the pocket go shows 
18:54  military time (24hr clock)
But if you click on the clock app it shows
6:59 PM (12hr clock)
No matter how many times I set it it is 1 hour off and will only display military time unless you click on to the click app which will show a 12 hour clock
Please fix

**Comment by Ninoh-FOX** [comment]
do you use esoteric or gmenu2x?

**Comment by Johnny56732** [comment]
Gmenu2x

**Comment by fornellas** [comment]
I don't recall the hardware having a RTC...

**Comment by Ninoh-FOX** [comment]
The hardware have RTC

**Comment by Ninoh-FOX** [comment]
the clock work fine in the last releases, closed
