### ISSUE TITLE
Cannot connect from PC when run Network icon

### ISSUE THREAD

**Issue by samart45** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#27]
After run Network icon.
I display.

IP addrs: usb0: 10.1.1.2
Login with user name: root
....

I select menu  login without password.
but I cannot ping to this ip and cannot FTP, telnet or SSH.

Thank you

**Comment by Ninoh-FOX** [comment]
Do you use the usb-c that arrive with the console package?

**Comment by samart45** [comment]
Yes. I use it.
I change other cable from my smartphone. I don't work too.

**Comment by Ninoh-FOX** [comment]
The cable that has the console is for only charge battery, anyway, you need a drivers for windows or not work.

**Comment by samart45** [comment]
Now. I can connect.
I install  PLAYGO-Kernel-update-1.0.4-2020-01-31.opk for update kernel.
It's work fine.
Thank you so much.

**Comment by Ninoh-FOX** [comment]
Ok
