### ISSUE TITLE
Include Rogue Update Manager from RG350 branch

### ISSUE THREAD

**Issue by Shut3n** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#28]
Hi,
Please include Rogue Update Manager and update linux-firmware package to the last version (16-03-2020) from RG350 branch on this PocketGo2/PlayGo one

Thank you

**Comment by Retro-Ninja** [comment]
why hasn't this been updated yet.

**Comment by Ninoh-FOX** [comment]
Because I am very busy in the work.

![IMG-20200409-WA0042](https://user-images.githubusercontent.com/17140259/78921839-d033e880-7a95-11ea-9a92-603629b215ec.jpg)

**Comment by Shut3n** [comment]
Wow, awesome task.. Hope you'll be well

**Comment by Ninoh-FOX** [comment]
I am remember now that the console not has a port OTG (not physically, the board has this.), so not is possible connect a wifi adapter, not is possible porter this opk.
