### ISSUE TITLE
PlayGo Version 1.0.5 Splash Screen needs to be updated.

### ISSUE THREAD

**Issue by Retro-Ninja** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#31]
Upon powering on the playgo device, the splash screen still indicates pocketgo v1.0.0, I suggest removing the version on the logo splash screen so that it can be used again without worries.

**Comment by Ninoh-FOX** [comment]
Oh, maybe I worng of file :p, thank for said me. I reload in a moment

**Comment by Ninoh-FOX** [comment]
fixed
