### ISSUE TITLE
Screen resolution is off on 1.0.6 firmware

### ISSUE THREAD

**Issue by renesdk** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#36]
With the new 1.0.6 firmware the resolution is somehow not correct. The text font is washed out, both in menus and games.
No settings in the emulator menues help with the problem.
I tried using the POWER+D-pad UP and DOWN, but it didn't work either.

Games are also displayed with washed out graphics.

I downgraded to 1.0.5 and eveything is fine on that firmware.

**Comment by Ninoh-FOX** [comment]
fixed, I go to close the theme.
