### ISSUE TITLE
Battery Indicator is always showing 100%

### ISSUE THREAD

**Issue by Bicbec** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#42]
Hi there!

I have a New PocketGo2v2 with its specific 1.0.8 firmware. The Battery indicator is always showing 100% battery, even after one hour of use. The software to check hardware issues is showing 100% too.

**Comment by vuribe1221** [comment]
I have the same issue. Version 1.0.4 didn't have this issue but after updating 1.0.8 the battery meter doesn't change from 100%. Booting into 1.0.4 works.

**Comment by Ninoh-FOX** [comment]
battery indicator WORKS FINE

![](https://raw.githubusercontent.com/Ninoh-FOX/POCKETGO2_ROGUE_CFW/master/screenshots/IMG_20200529_122144.jpg)<br>

Is normal, I said NORMAL, that the 100% not change in a hour aprox.
