### ISSUE TITLE
Lost one audio channel in v1.0.8 

### ISSUE THREAD

**Issue by Turko577** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#43]
I just installed 1.0.8 for my pg2v2, apparently everything is fine, but now headphone Jack only producing sound through one channel (left), I already tried several hearing aids (two and three pin) and the same thing happened with all of them.
Previously it worked, I have a backup of the vanilla version, but now it is not grabbing there either.
Do not force the jack, nor is it loose, so I do not think it is hardware, is it possible that it is the alsamixer?

**Comment by Ninoh-FOX** [comment]
No, alsamixer send two channels sound always, your problem is of the hardware, surery you are lose the last pin of the jack connector.
