### ISSUE TITLE
Battery level doesn't report accurately

### ISSUE THREAD

**Issue by pfroo40** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#44]
I have a PocketGo v2.1 and after flashing 1.0.8, my battery charge level does not report accurately at all. It typically shows 100%, or jumps around a bit, even when the battery light starts flashing low. It persists through multiple reflashes and after multiple charge cycles.

**Comment by Turko577** [comment]
The same thing is happening to me, after the first charge with 1.0.8 my battery only shows 100%.

**Comment by Guzella** [comment]
Same issue after updating from 1.0.4 to 1.0.8.

**Comment by Ninoh-FOX** [comment]
fixed in the new release
