### ISSUE TITLE
FFPlay player stops working after around 5 mins of video playback

### ISSUE THREAD

**Issue by Angel266333** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#48]
The built in player in version 1.0.9 stops working whenever I play a movie that was converted by Handbrake with the Apple 240p30 preset. It happens around 5 minutes of playback into the video and I would need to skip to the specific section where it cut off.

**Comment by Angel266333** [comment]
This happened with a PocketGo 2 device (not V2) fyi.

**Comment by Ninoh-FOX** [comment]
This is a limitation of the program, not of the cfw
