### ISSUE TITLE
Internal sd card now almost full

### ISSUE THREAD

**Issue by Johnny56732** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#5]
After this update the internal sd card now shows over 27 gigs used out of 28
Before this new update there was over 27gigs of space avalible

**Comment by Ninoh-FOX** [comment]
do you have sure? This is very strange, I never sound some similar.

**Comment by Johnny56732** [comment]
Would you like a picture of it?

**Comment by Johnny56732** [comment]
Sorry my mistake I was looking at it wrong
It looks like this
27.6/28.2GIB
