### ISSUE TITLE
Changing section for opk shortcuts is not saved

### ISSUE THREAD

**Issue by Drumaster78** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#51]
Moving a shortcut from one section to another is not saved.

Hardware: PocketGo2 v2
Software: Rogue CFW 1.0.9 for PocketGo2 v2

Steps to reproduce:
1. Use Edit function on any opk shortcut
2. Move the shortcut to another section
3. Restart GMenu2X (Power+Select or reboot the console)
4. Notice that the change was not saved as the shortcut is in its former section

**Comment by Ninoh-FOX** [comment]
The opk need has the section name in his internar config for that this did saving.
