### ISSUE TITLE
[NICE TO HAVE] Possibility to set screen brightness to 0

### ISSUE THREAD

**Issue by Drumaster78** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#53]
Would be nice to be able to turn off screen brightness when you want to listen to your favorite tunes on both PocketGo2 v2 and RG350 instead of having it set to the minimum. We were able to do that with the stock firmware.

**Comment by Ninoh-FOX** [comment]
This is not has the valor 0 active because the screen go to max brightess when you exit of black screen, for this, I am put a min valor and not 0.

**Comment by Ninoh-FOX** [comment]
done in update 1.1

**Comment by Drumaster78** [comment]
Yes I saw that, that works fine, thanks @Ninoh-FOX !
