### ISSUE TITLE
which 1.0.9 Rogue firmware to flash for PlayGo with motherboard 2020-03-24 v1.5?

### ISSUE THREAD

**Issue by lambeeboy** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#54]
Hi Guys,

Need a bit of help for my PlayGo.
My version is (I believe) the latest one with reset button and no label on the menu button.
I have also opened up the console, and found that mine is equipped with mobo v1.5 dated 2020-03-24:
![image](https://user-images.githubusercontent.com/76072199/102271576-df6e0e80-3f1f-11eb-9010-4615f61fa71f.png)

Can someone please advise which firmware I need to flash to get this awesome Rogue 1.0.9?

Many thanks in advance,

lambeeboy

**Comment by Ninoh-FOX** [comment]
You need de version PG2v2

https://github.com/Ninoh-FOX/POCKETGO2_ROGUE_CFW/releases/download/v1.0.9/sd_image_POCKETGO2V2.bin
