### ISSUE TITLE
a question about updating, PS: i updated it but there is something wrong

### ISSUE THREAD

**Issue by adi170-alt** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#57]
I have a and might want to update it but i'm worried i'll have to reinstall my custom skin, emulators and games like quake 2, so when i'm going to update it will i keep that stuff?, or will it just remove the things?

**Comment by Ninoh-FOX** [comment]
no, you don't lose nothing for update

**Comment by adi170-alt** [comment]
[https://i.imgur.com/dTcIiQr.jpg](url)

HELP what do i need to do now???

**Comment by adi170-alt** [comment]
I created a new issue and I'm gonna clos this one, the issue i writed is the same as in the new issue
