### ISSUE TITLE
Please add Retroarch to this firmware

### ISSUE THREAD

**Issue by Cibomatto2002** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#60]
They now have Retroarch for the Pocket go 2V2 and Pocket go 2 it comes with a lot of cores allready installed so there is nothing to download but Retroarch.

https://buildbot.libretro.com/nightly/dingux/mips32/

**Comment by Ninoh-FOX** [comment]
You can use this autoinstaler from a friend.

https://github.com/eduardofilo/RG350_ra_installer/releases/tag/v2021-03-06

**Comment by Cibomatto2002** [comment]
Thank you
