### ISSUE TITLE
request to add something to the software

### ISSUE THREAD

**Issue by adi170-alt** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#62]
I don't know if I wrote the title good, but I have a playgo, and it does not have a hdmi out, but it has a USB-c out, I have a USB-c to hdmi converter lying around for my school Chromebook, it would be fun if I just put the converter in my handheld and just play by hmdi, so can u guys add that feature?

**Comment by Ninoh-FOX** [comment]
Not is possible, anyway, this console not has otg port

**Comment by adi170-alt** [comment]
ohh okey
