### ISSUE TITLE
fba (cps1/2) games don't work

### ISSUE THREAD

**Issue by adi170-alt** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#64]
https://imgur.com/a/U7NBiEP
I tried to play a few cps 1 and 2 games but every way I try to play them that in the picture pops up or when I click nothing happens,
I tried to use XMAME, but that also did not work because the games did not show(I putted the games in the rom's folder). It is hard to explain why, but I don't use the fba emulator that came when you flashed it on a sd-card.
I just install roms from websites and after that I don't open the zip file but just put the zip files in my roms folders

**Comment by Ninoh-FOX** [comment]
Are you really sure you don't have the right romset before blaming the firmware?

![](https://fotos.subefotos.com/b7119f6c5d3f902036bd371835800f4eo.jpg)

**Comment by Ninoh-FOX** [comment]
Are you really sure you have the roms in the right place before blaming the firmware?
![](https://fotos.subefotos.com/4953fbf4de9b60cbff071cbca03e2a6eo.jpg)

**Comment by Ninoh-FOX** [comment]
you problem, not is the firmware/emulator, is that your roms versions **not is the correct** for the emulators.

**Comment by adi170-alt** [comment]
> Are you really sure you don't have the right romset before blaming the firmware?
> 
> ![](https://camo.githubusercontent.com/fdedbf71330c428fecbe1d5c725c6bfca4b99375bf7dff8228f611ce6a5ba28c/68747470733a2f2f666f746f732e73756265666f746f732e636f6d2f62373131396636633564336639303230333662643337313833353830306634656f2e6a7067)

I don't blame the firmware, it is just the only place that I can come to and ask questions, because I'm scarred that I am going to get hate or almost no attention on Reddit.

**Comment by Ninoh-FOX** [comment]
as I have already told you, you need the correct romset of roms, I can not give you support in that

**Comment by adi170-alt** [comment]
I know
