### ISSUE TITLE
Make a Wiki

### ISSUE THREAD

**Issue by puddlejumper90** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#65]
## Better Documentation

Looks like it has been a while since this repo has been updated and there is a ton of assumptions that everyone should already know what they are doing.  I would love to promote this repo, but I am really looking for better documentation.

**Consider adding the following:**

1. Simple step-by-step firmware installation to a blank SD card.
2. Simple step-by-step instructions on how to update the firmware when a new update is available

**Additional Question**

Where can stakeholders go to support this project? I am an investor and I don't mind putting money into this project.

**Comment by omgmog** [comment]
## Simple step-by-step firmware installation to a blank SD card.

Download one of the `sd_image.bin` files for your device, e.g. the v1.1 `sd_image_PocketGo2.bin` from [here](https://github.com/Ninoh-FOX/POCKETGO2_ROGUE_CFW/releases/tag/v1.1)

Write the `sd_image.bin` to a blank SD card (this will erase everything on the card) using your favourite tool, such as [Win32DiskImager](https://win32diskimager.org), or with `dd`:

```
sudo dd if=sd_image.bin of=/dev/{your blank SD} bs=1m
```

Once that has finished, insert the SD in to your device, turn it on, and wait for the initial install/resize scripts to run. This should take a couple of minutes.

## Simple step-by-step instructions on how to update the firmware when a new update is available

Download the update `.opk` file for your device, e.g. the v1.3 `pocketgo2-update-1.3-2021-03-17.opk` from [here](https://github.com/Ninoh-FOX/POCKETGO2_ROGUE_CFW/releases/tag/v1.3)

Stick the `.opk` file on an SD card, or transfer it to your device over SSH.

On the device, open `DinguxCmdr` and copy the `.opk` from your SD card to `/media/data/apps`.

Close `DinguxCmdr` and you will now see the update in your apps menu.

Launch the updater from the menu and go through the update process.

If you have trouble booting after an update you can boot a previous kernel by holding `Y` as you boot.
