### ISSUE TITLE
Megadrive/Genesis emulator (SRAM support for 8MB games and above)

### ISSUE THREAD

**Issue by Shut3n** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#70]
A couple of months ago Genesis-Plus-GX and Picodrive src trees received a fix to support SRAM support for games larger than 8MB (for example, Demons of Asteborg and some others)

Could you pack'em on opk format to make them work for ROGUE CFW? (RG350, PocketGo2 & PlayGo)

Thank you for your customs

**Comment by Ninoh-FOX** [comment]
I remember that I updated the picodriver emulator with this feacture.

**Comment by Shut3n** [comment]
I'll give another try to it then and check
