### ISSUE TITLE
1 button press registers as 2

### ISSUE THREAD

**Issue by sub-atomic** [Ninoh-FOX/POCKETGO2_ROGUE_CFW#9]
I was running 1.0.2, and in the menus, some button presses would register as two presses. For example, changing the name of the Emulators section to Systems, I'd end up with "Sysstemms". Pressing the d-pad would jump two icons instead of one. This would happen on and off every 4th or 5th button press.

As soon as I put the stock firmware back, this problem went away.

**Comment by Ninoh-FOX** [comment]
fixed in the new release
